language: node_js
node_js:
  - "5.1"
before_script:
  - npm install
  - npm install -g eslint ember-cli
  - bower install
script:
  - ember build -prod
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "asarudick.com"
  region: us-west-1
  local_dir: dist
